version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: yes
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: ec2-user
    mode: 664
    type:
      - file
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: ec2-user
    mode: 775
    type:
      - directory
hooks:
#    BeforeInstall:
#     - location: scripts/install.sh
#       runas: root
    ApplicationStart:
      - location: cd-scripts/restart.sh
        runas: root
